// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserService.Db;

#nullable disable

namespace UserService.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20250204000000_AddEmailToUser")]
    partial class AddEmailToUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);
            modelBuilder.Entity("UserService.Db.Role", b =>
                {
                    b.Property<int>("RoleId").HasColumnType("integer");
                    b.Property<string>("Name").IsRequired().HasColumnType("text");
                    b.HasKey("RoleId");
                    b.ToTable("Roles");
                });
            modelBuilder.Entity("UserService.Db.User", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer").HasColumnName("id");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("Email").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("email");
                    b.Property<string>("Name").HasMaxLength(255).HasColumnType("character varying(255)").HasColumnName("name");
                    b.Property<byte[]>("Password").IsRequired().HasColumnType("bytea").HasColumnName("password");
                    b.Property<int>("RoleId").HasColumnType("integer");
                    b.Property<byte[]>("Salt").IsRequired().HasColumnType("bytea").HasColumnName("salt");
                    b.HasKey("Id").HasName("users_pkey");
                    b.HasIndex("Email").IsUnique();
                    b.HasIndex("RoleId");
                    b.ToTable("users", (string)null);
                });
            modelBuilder.Entity("UserService.Db.User", b =>
                {
                    b.HasOne("UserService.Db.Role", "Role").WithMany("Users").HasForeignKey("RoleId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Role");
                });
            modelBuilder.Entity("UserService.Db.Role", b => { b.Navigation("Users"); });
#pragma warning restore 612, 618
        }
    }
}
